apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.vrtc.name }}
  annotations:  
    icp.management.ibm.com/rewrite-target: "/"
spec:
#  tls:
#  - hosts:
#    - mec-poc.us-south.containers.appdomain.cloud
#    secretName: mec-poc
  rules:
    - http:
       paths:
       - path: /vrtc-intel
         backend:
           serviceName: {{ .Values.vrtc.service.name.x86 }}
           servicePort: 5000
       - path: /vrtc-power
         backend:
           serviceName: {{ .Values.vrtc.service.name.ppc64le }}
           servicePort: 5000