apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.vrtc.name }}
  annotations:  
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/proxy-read-timeout: "60s"
    ingress.kubernetes.io/proxy-send-timeout: "60s"
    ingress.kubernetes.io/proxy-connect-timeout: "60s"
  namespace: object-detection
spec:
  rules:
    - http:
       paths:
       - path: /vrtc-intel
         backend:
           serviceName: {{ .Values.vrtc.service.name.x86 }}
           servicePort: 5000
       - path: /vrtc-power
         backend:
           serviceName: {{ .Values.vrtc.service.name.ppc64le }}
           servicePort: 5000