apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.vrtc.deployment.name.ppc64le }}
  labels:
    app: {{ template "vrtc.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    component: {{ .Values.vrtc.deployment.name.ppc64le }}
spec:
  replicas: {{ .Values.replicaCount.ppc64le }}
  selector:
    matchLabels:
      app: {{ template "vrtc.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.vrtc.deployment.name.ppc64le }}
  template:
    metadata:
      labels:
        app: {{ template "vrtc.name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.vrtc.deployment.name.ppc64le }}
    spec:
      containers:
        - name: {{ .Values.vrtc.name }}
          image: "{{ .Values.vrtc.image.ppc64le.repository }}:{{ .Values.vrtc.image.ppc64le.tag }}"
          imagePullPolicy: {{ .Values.vrtc.image.ppc64le.pullPolicy }}
{{ if (.Values.vrtc.enableGPU) and eq .Values.vrtc.enableGPU "yes" }}
          resources:
            limits:
              alpha.kubernetes.io/nvidia-gpu: "{{.Values.vrtc.gpuNum}}"
{{ end }}         
          ports:
            - name: {{ .Values.vrtc.name }}
              containerPort: 5000
              protocol: TCP
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values: ["ppc64le"]