apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.vrtc.name }}
#  annotations:  
#    ingress.bluemix.net/rewrite-path: "serviceName=objectdetection rewrite=/"
spec:
#  tls:
#  - hosts:
#    - mec-poc.us-south.containers.appdomain.cloud
#    secretName: mec-poc
  rules:
    - http:
       paths:
       - path: /intel
         backend:
           serviceName: {{ .Values.vrtc.service.name.x86 }}
           servicePort: 5000
       - path: /power
         backend:
           serviceName: {{ .Values.vrtc.service.name.x86 }}
           servicePort: 5000